package com.example.agromart.navigation

enum class AgroMartScreen {
    MAIN_SCREEN,
    PRODUCT_DESCRIPTION_SCREEN,
    SPLASH_SCREEN,
    BUY_SELL_SCREEN,
    BUYER_ITEM_LIST_SCREEN,
    NEARBY_SELLER_SCREEN,
    DELIVERY_AGENT_SCREEN,
    PROFILE_SCREEN,
    CATEGORY_SCREEN,
    LOGIN_SCREEN,
    EDIT_CARD,
    SALES_PAGE_CARD,
    SALES_PAGE,
    LIST_OF_PROD,
    PRODUCT_DESCRIPTION_SELLER_SCREEN_SECOND,
    CHAT_BOT_SCREEN,
    BLOG_SCREEN,
    BUYING_SCREEN,
    MY_FARM,
    SELLER_PRODUCT_VIEW
}